resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/macdonda/concourse-spring-boot-maven.git
    branch: master
jobs:
- name: package
  plan:
  - get: source-code
    trigger: true
  - aggregate:
    - task: package-job-service
      privileged: true
      file: source-code/ci/tasks/package.yml
      params:
        project: job-service
    - task: package-poweron-connect-service
      privileged: true
      file: source-code/ci/tasks/package.yml
      params:
        project: poweron-connect-service
